### Question 1

What's the version of Pandas that you installed?

In [1]:
import pandas as pd

In [2]:
pd.__version__

'1.3.4'

Getting the data

In [3]:
df = pd.read_csv('raw.githubusercontent.com_alexeygrigorev_datasets_master_housing.csv')
df.shape

(20640, 10)

In [4]:
df.T

0         1         2         3         4      \
longitude            -122.23   -122.22   -122.24   -122.25   -122.25   
latitude               37.88     37.86     37.85     37.85     37.85   
housing_median_age      41.0      21.0      52.0      52.0      52.0   
total_rooms            880.0    7099.0    1467.0    1274.0    1627.0   
total_bedrooms         129.0    1106.0     190.0     235.0     280.0   
population             322.0    2401.0     496.0     558.0     565.0   
households             126.0    1138.0     177.0     219.0     259.0   
median_income         8.3252    8.3014    7.2574    5.6431    3.8462   
median_house_value  452600.0  358500.0  352100.0  341300.0  342200.0   
ocean_proximity     NEAR BAY  NEAR BAY  NEAR BAY  NEAR BAY  NEAR BAY   

                       5         6         7         8         9      ...  \
longitude            -122.25   -122.25   -122.25   -122.26   -122.25  ...   
latitude               37.85     37.84     37.84     37.84     37.84  ...   
housing_median_age      52.0      52.0      52.0      42.0      52.0  ...   
total_rooms            919.0    2535.0    3104.0    2555.0    3549.0  ...   
total_bedrooms         213.0     489.0     687.0     665.0     707.0  ...   
population             413.0    1094.0    1157.0    1206.0    1551.0  ...   
households             193.0     514.0     647.0     595.0     714.0  ...   
median_income         4.0368    3.6591      3.12    2.0804    3.6912  ...   
median_house_value  269700.0  299200.0  241400.0  226700.0  261100.0  ...   
ocean_proximity     NEAR BAY  NEAR BAY  NEAR BAY  NEAR BAY  NEAR BAY  ...   

                       20630     20631     20632    20633     20634    20635  \
longitude            -121.32    -121.4   -121.45  -121.53   -121.56  -121.09   
latitude               39.29     39.33     39.26    39.19     39.27    39.48   
housing_median_age      11.0      15.0      15.0     27.0      28.0     25.0   
total_rooms           2640.0    2655.0    2319.0   2080.0    2332.0   1665.0   
total_bedrooms         505.0     493.0     416.0    412.0     395.0    374.0   
population            1257.0    1200.0    1047.0   1082.0    1041.0    845.0   
households             445.0     432.0     385.0    382.0     344.0    330.0   
median_income         3.5673    3.5179     3.125   2.5495    3.7125   1.5603   
median_house_value  112000.0  107200.0  115600.0  98300.0  116800.0  78100.0   
ocean_proximity       INLAND    INLAND    INLAND   INLAND    INLAND   INLAND   

                      20636    20637    20638    20639  
longitude           -121.21  -121.22  -121.32  -121.24  
latitude              39.49    39.43    39.43    39.37  
housing_median_age     18.0     17.0     18.0     16.0  
total_rooms           697.0   2254.0   1860.0   2785.0  
total_bedrooms        150.0    485.0    409.0    616.0  
population            356.0   1007.0    741.0   1387.0  
households            114.0    433.0    349.0    530.0  
median_income        2.5568      1.7   1.8672   2.3886  
median_house_value  77100.0  92300.0  84700.0  89400.0  
ocean_proximity      INLAND   INLAND   INLAND   INLAND  

[10 rows x 20640 columns]

### Question 2 

How many columns are in the dataset?

In [5]:
len(df.columns)

10

### Question 3

Which columns in the dataset have missing values?

In [6]:
df.isna().sum()

longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        207
population              0
households              0
median_income           0
median_house_value      0
ocean_proximity         0
dtype: int64

### Question 4

How many unique values does the ocean_proximity column have?

In [7]:
len(df.ocean_proximity.unique())

5

### Question 5

What's the average value of the median_house_value for the houses located near the bay?

In [8]:
average_value = df[df['ocean_proximity'] == 'NEAR BAY']['median_house_value'].mean()

print("The average value of the median house value for houses near the bay is:", average_value)


The average value of the median house value for houses near the bay is: 259212.31179039303


### Question 6

1. Calculate the average of total_bedrooms column in the dataset.

In [9]:
avg_total_bedrooms = df.total_bedrooms.mean()
avg_total_bedrooms

537.8705525375618

2. Use the fillna method to fill the missing values in total_bedrooms with the mean value from the previous step.

In [10]:
df['total_bedrooms'].fillna(avg_total_bedrooms, inplace=True)

In [11]:
df['total_bedrooms'].isna().sum()

0

 3. Now, calculate the average of total_bedrooms again.

In [12]:
new_avg_total_bedrooms = df.total_bedrooms.mean()
print("new_avg_total_bedrooms:", new_avg_total_bedrooms)

new_avg_total_bedrooms: 537.8705525375639


4. Has it changed? (take into account only 3 digits after the decimal point.)

No

### Question 7

1. Select all the options located on islands.

In [13]:
rows_with_island = df[df['ocean_proximity'] == 'ISLAND']
rows_with_island

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
8314    -118.32     33.35                27.0       1675.0           521.0   
8315    -118.33     33.34                52.0       2359.0           591.0   
8316    -118.32     33.33                52.0       2127.0           512.0   
8317    -118.32     33.34                52.0        996.0           264.0   
8318    -118.48     33.43                29.0        716.0           214.0   

      population  households  median_income  median_house_value  \
8314       744.0       331.0         2.1579            450000.0   
8315      1100.0       431.0         2.8333            414700.0   
8316       733.0       288.0         3.3906            300000.0   
8317       341.0       160.0         2.7361            450000.0   
8318       422.0       173.0         2.6042            287500.0   

     ocean_proximity  
8314          ISLAND  
8315          ISLAND  
8316          ISLAND  
8317          ISLAND  
8318          ISLAND

2. Select only columns housing_median_age, total_rooms, total_bedrooms.

In [14]:
selected_columns = rows_with_island[['housing_median_age', 'total_rooms', 'total_bedrooms']]
selected_columns

housing_median_age  total_rooms  total_bedrooms
8314                27.0       1675.0           521.0
8315                52.0       2359.0           591.0
8316                52.0       2127.0           512.0
8317                52.0        996.0           264.0
8318                29.0        716.0           214.0

3. Get the underlying NumPy array. Let's call it X

In [15]:
import numpy as np

In [16]:
X = selected_columns.values
X

array([[  27., 1675.,  521.],
       [  52., 2359.,  591.],
       [  52., 2127.,  512.],
       [  52.,  996.,  264.],
       [  29.,  716.,  214.]])

4. Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.

In [17]:
X.T

array([[  27.,   52.,   52.,   52.,   29.],
       [1675., 2359., 2127.,  996.,  716.],
       [ 521.,  591.,  512.,  264.,  214.]])

In [18]:
XTX = np.dot(X.T, X)
XTX

array([[9.6820000e+03, 3.5105300e+05, 9.1357000e+04],
       [3.5105300e+05, 1.4399307e+07, 3.7720360e+06],
       [9.1357000e+04, 3.7720360e+06, 9.9835800e+05]])

5. Compute the inverse of XTX.

In [19]:
inverse_XTX = np.linalg.inv(XTX)
inverse_XTX

array([[ 9.19403586e-04, -3.66412216e-05,  5.43072261e-05],
       [-3.66412216e-05,  8.23303633e-06, -2.77534485e-05],
       [ 5.43072261e-05, -2.77534485e-05,  1.00891325e-04]])

6. Create an array y with values [950, 1300, 800, 1000, 1300]

In [20]:
y = np.array([950, 1300, 800, 1000, 1300])
y

array([ 950, 1300,  800, 1000, 1300])

7. Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.

In [21]:
p = np.dot(inverse_XTX, X.T)
p

array([[-0.00825608, -0.00653208, -0.00232159,  0.02565144,  0.01204934],
       [-0.00165852,  0.0011141 ,  0.00139656, -0.00103215, -0.00110698],
       [ 0.00754365, -0.00301964, -0.00455125,  0.00181685,  0.00329418]])

In [22]:
w = np.dot(p,y)
w

array([23.12330961, -1.48124183,  5.69922946])

8. What's the value of the last element of w?

In [23]:
w[-1]


5.699229455065586